src/Entity/Language.php
<?php

namespace App\Entity;

use App\Repository\LanguageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Parse\SpaceDelimitedParser;
use App\Parse\JapaneseParser;
use App\Parse\ClassicalChineseParser;
use App\Parse\TurkishParser;
use Symfony\Component\Yaml\Yaml;

#[ORM\Entity(repositoryClass: LanguageRepository::class)]
#[ORM\Table(name: 'languages')]
class Language
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'LgID', type: Types::SMALLINT)]
    private ?int $LgID = null;

    #[ORM\Column(name: 'LgName', length: 40)]
    private ?string $LgName = null;

    #[ORM\Column(name: 'LgDict1URI', length: 200)]
    #[Assert\Regex('/###/', message: 'Please specify the term placeholder with ###')]
    private ?string $LgDict1URI = null;

    #[ORM\Column(name: 'LgDict2URI', length: 200)]
    #[Assert\Regex('/###/', message: 'Please specify the term placeholder with ###')]
    private ?string $LgDict2URI = null;

    #[ORM\Column(name: 'LgGoogleTranslateURI', length: 200)]
    #[Assert\Regex('/###/', message: 'Please specify the term placeholder with ###')]
    private ?string $LgGoogleTranslateURI = null;

    #[ORM\Column(name: 'LgCharacterSubstitutions', length: 500)]
    private ?string $LgCharacterSubstitutions = "´='|`='|’='|‘='|...=…|..=‥";

    #[ORM\Column(name: 'LgRegexpSplitSentences', length: 500)]
    private ?string $LgRegexpSplitSentences = '.!?';

    #[ORM\Column(name: 'LgExceptionsSplitSentences', length: 500)]
    private ?string $LgExceptionsSplitSentences = 'Mr.|Mrs.|Dr.|[A-Z].|Vd.|Vds.';

    #[ORM\Column(name: 'LgRegexpWordCharacters', length: 500)]
    private ?string $LgRegexpWordCharacters = 'a-zA-ZÀ-ÖØ-öø-ȳáéíóúÁÉÍÓÚñÑ';

    #[ORM\Column(name: 'LgRemoveSpaces')]
    private ?bool $LgRemoveSpaces = false;

    #[ORM\Column(name: 'LgSplitEachChar')]
    private ?bool $LgSplitEachChar = false;

    #[ORM\Column(name: 'LgRightToLeft')]
    private ?bool $LgRightToLeft = false;

    #[ORM\Column(name: 'LgShowRomanization')]
    private bool $LgShowRomanization = false;

    #[ORM\Column(name: 'LgParserType', length: 20)]
    private string $LgParserType = 'spacedel';

    #[ORM\OneToMany(targetEntity: 'Book', mappedBy: 'Language', fetch: 'EXTRA_LAZY')]
    private Collection $books;

    #[ORM\OneToMany(targetEntity: 'Term', mappedBy: 'language', fetch: 'EXTRA_LAZY')]
    private Collection $terms;

    public function __construct()
    {
        $this->books = new ArrayCollection();
        $this->terms = new ArrayCollection();
    }

    public function __toString(): string {
        return $this->LgID . ': ' . $this->LgName;
    }

    public function getLgID(): ?int
    {
        return $this->LgID;
    }

    public function setLgID(int $LgID): self
    {
        $this->LgID = $LgID;

        return $this;
    }

    public function getLgName(): ?string
    {
        return $this->LgName;
    }

    public function setLgName(string $LgName): self
    {
        $this->LgName = $LgName;

        return $this;
    }

    public function getLgDict1URI(): ?string
    {
        return $this->LgDict1URI;
    }

    public function setLgDict1URI(string $LgDict1URI): self
    {
        $this->LgDict1URI = $LgDict1URI;

        return $this;
    }

    public function getLgDict2URI(): ?string
    {
        return $this->LgDict2URI;
    }

    public function setLgDict2URI(?string $LgDict2URI): self
    {
        $this->LgDict2URI = $LgDict2URI;

        return $this;
    }

    public function getLgGoogleTranslateURI(): ?string
    {
        return $this->LgGoogleTranslateURI;
    }

    public function setLgGoogleTranslateURI(string $LgGoogleTranslateURI): self
    {
        $this->LgGoogleTranslateURI = $LgGoogleTranslateURI;

        return $this;
    }

    public function getLgCharacterSubstitutions(): ?string
    {
        return $this->LgCharacterSubstitutions;
    }

    public function setLgCharacterSubstitutions(string $LgCharacterSubstitutions): self
    {
        $this->LgCharacterSubstitutions = $LgCharacterSubstitutions;

        return $this;
    }

    public function getLgRegexpSplitSentences(): ?string
    {
        return $this->LgRegexpSplitSentences;
    }

    public function setLgRegexpSplitSentences(string $LgRegexpSplitSentences): self
    {
        $this->LgRegexpSplitSentences = $LgRegexpSplitSentences;

        return $this;
    }

    public function getLgExceptionsSplitSentences(): ?string
    {
        return $this->LgExceptionsSplitSentences;
    }

    public function setLgExceptionsSplitSentences(string $LgExceptionsSplitSentences): self
    {
        $this->LgExceptionsSplitSentences = $LgExceptionsSplitSentences;

        return $this;
    }

    public function getLgRegexpWordCharacters(): ?string
    {
        return $this->LgRegexpWordCharacters;
    }

    public function setLgRegexpWordCharacters(string $LgRegexpWordCharacters): self
    {
        $this->LgRegexpWordCharacters = $LgRegexpWordCharacters;

        return $this;
    }

    public function isLgRemoveSpaces(): ?bool
    {
        return $this->LgRemoveSpaces;
    }

    public function setLgRemoveSpaces(bool $LgRemoveSpaces): self
    {
        $this->LgRemoveSpaces = $LgRemoveSpaces;

        return $this;
    }

    public function isLgSplitEachChar(): ?bool
    {
        return $this->LgSplitEachChar;
    }

    public function setLgSplitEachChar(bool $LgSplitEachChar): self
    {
        $this->LgSplitEachChar = $LgSplitEachChar;

        return $this;
    }

    public function isLgRightToLeft(): ?bool
    {
        return $this->LgRightToLeft;
    }

    public function setLgRightToLeft(bool $LgRightToLeft): self
    {
        $this->LgRightToLeft = $LgRightToLeft;

        return $this;
    }

    public function getLgShowRomanization(): bool
    {
        return $this->LgShowRomanization;
    }

    public function setLgShowRomanization(bool $b): self
    {
        $this->LgShowRomanization = $b;
        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function getActiveBooks(): Collection
    {
        $criteria = Criteria::create()
            ->andWhere(Criteria::expr()->eq('Archived', 0));

        // Psalm says that this method isn't defined, but a) the code works,
        // and b) symfony docs say this works.
        /**
         * @psalm-suppress UndefinedInterfaceMethod
         */
        return $this->books->matching($criteria);
    }

    /**
     * @return Collection|Term[]
     */
    public function getTerms(): Collection
    {
        return $this->terms;
    }

    public function setLgParserType(string $s): self
    {
        $this->LgParserType = $s;
        return $this;
    }

    public function getLgParserType(): string
    {
        return $this->LgParserType;
    }

    public function getParser()
    {
        switch ($this->LgParserType) {
        case 'spacedel':
            return new SpaceDelimitedParser();
        case 'classicalchinese':
            return new ClassicalChineseParser();
        case 'japanese':
            return new JapaneseParser();
        case 'turkish':
            return new TurkishParser();
        default:
            throw new \Exception("Unknown parser type {$this->LgParserType} for {$this->getLgName()}");
        }
    }
    
    public function getParsedTokens(string $s): array
    {
        return $this->getParser()->getParsedTokens($s, $this);
    }

    /** Convenience method only. */
    public function getLowercase(string $s): string
    {
        return $this->getParser()->getLowercase($s);
    }

    /**
     * Language "factories" to create sensible defaults.
     * Returns unsaved entities.
     */

    /**
     * Demo files are stored in root/demo/*.yaml.
     */
    public static function fromYaml($filename): Language {
        $d = Yaml::parseFile($filename);

        $lang = new Language();

        $load = function($key, $method) use ($d, $lang) {
            if (! array_key_exists($key, $d))
                return;

            $val = $d[$key];

            // Have to put "\*" for external dicts in yaml,
            // but those should be saved as "*" only.
            // if (str_starts_with($val, '\*'))

            // Bools are special
            if (strtolower($val) == 'true')
                $val = true;
            if (strtolower($val) == 'false')
                $val = false;

            $lang->{$method}($d[$key]);
        };

        # Input fields on the user form, e.g.
        # http://localhost:9999/language/1/edit
        $mappings = [
            'name' => 'setLgName',
            'dict_1' => 'setLgDict1URI',
            'dict_2' => 'setLgDict2URI',
            'sentence_translation' => 'setLgGoogleTranslateURI',
            'show_romanization' => 'setLgShowRomanization',
            'right_to_left' => 'setLgRightToLeft',

            # Parsing
            'parser_type' => 'setLgParserType',
            'character_substitutions' => 'setLgCharacterSubstitutions',
            'split_sentences' => 'setLgRegexpSplitSentences',
            'split_sentence_exceptions' => 'setLgExceptionsSplitSentences',
            'word_chars' => 'setLgRegexpWordCharacters',
        ];

        foreach (array_keys($d) as $key) {
            $funcname = $mappings[$key];
            if ($funcname != '') {
                $load($key, $funcname);
            }
        }

        return $lang;
    }


    public static function getPredefined(): array {
        $demoglob = dirname(__FILE__) . '/../../demo/languages/*.yaml';
        $ret = [];
        foreach(glob($demoglob) as $f) {
            $ret[] = Language::fromYaml($f);
        }

src/Controller/LanguageController.php
<?php

namespace App\Controller;

use App\Entity\Language;
use App\Form\LanguageType;
use App\Repository\LanguageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Filesystem\Path;

#[Route('/language')]
class LanguageController extends AbstractController
{
    #[Route('/index', name: 'app_language_index', methods: ['GET'])]
    public function index(LanguageRepository $languageRepository): Response
    {
        return $this->render('language/index.html.twig', [
            'languages' => $languageRepository->findAll(),
        ]);
    }

    #[Route('/new/{template?-}', name: 'app_language_new', methods: ['GET', 'POST'])]
    public function new(string $template, Request $request, LanguageRepository $languageRepository): Response
    {
        $predefined = array_values(Language::getPredefined());
        $language = new Language();
        $template_lc = strtolower($template);
        $cands = array_filter($predefined, fn($p) => $template_lc == strtolower($p->getLgName()));
        if (count($cands) > 0) {
            // dump($cands);
            $language = array_values($cands)[0];
        }

        $form = $this->createForm(LanguageType::class, $language);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $languageRepository->save($language, true);
            return $this->redirectToRoute('app_language_index', [], Response::HTTP_SEE_OTHER);
        }


        $langnames = array_map(fn($p) => $p->getLgName(), $predefined);
        array_unshift($langnames, '-');
        return $this->renderForm('language/new.html.twig', [
            'predefined' => $langnames,
            'language' => $language,
            'form' => $form,
        ]);
    }

    #[Route('/{LgID}/edit', name: 'app_language_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Language $language, LanguageRepository $languageRepository): Response
    {
        $form = $this->createForm(LanguageType::class, $language);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $languageRepository->save($language, true);

            return $this->redirectToRoute('app_language_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('language/edit.html.twig', [
            'language' => $language,
            'form' => $form,
        ]);
    }

    #[Route('/{LgID}', name: 'app_language_delete', methods: ['POST'])]
    public function delete(Request $request, Language $language, LanguageRepository $languageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$language->getLgID(), $request->request->get('_token'))) {
            $languageRepository->remove($language, true);
        }

        return $this->redirectToRoute('app_language_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/jsonlist', name: 'app_language_jsonlist', methods: ['GET'])]
    public function jsonlist(LanguageRepository $languageRepository): Response
    {
        $langs = $languageRepository->findAll();
        $ret = [];
        foreach ($langs as $lang) {
            $termdicts = [
                $lang->getLgDict1URI(),
                $lang->getLgDict2URI()
            ];
            $termdicts = array_filter($termdicts, fn($s) => $s != null);
            $h = [
                'term' => $termdicts,
                'sentence' => $lang->getLgGoogleTranslateURI()
            ];
            $ret[$lang->getLgID()] = $h;
        }
        return $this->json($ret);
    }

}

templates/language/_delete_form.html.twig
<form method="post" action="{{ path('app_language_delete', {'LgID': language.LgID}) }}" onsubmit="return confirm('WARNING: deleting a language deletes all its books and defined terms.  You may want to make a backup first (from the Home screen).  Are you *absolutely* sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ language.LgID) }}">
    <button class="btn">Delete</button>
</form>

templates/language/_form.html.twig
{% form_theme form 'form_table_layout.html.twig' %}

{{ form_start(form) }}

<table id="language">
  <tbody>

    {{ form_row(form.LgName) }}
    {{ form_row(form.LgDict1URI) }}
    {{ form_row(form.LgDict2URI) }}
    {{ form_row(form.LgGoogleTranslateURI) }}
    {{ form_row(form.LgShowRomanization) }}
    {{ form_row(form.LgRightToLeft) }}

    <tr style="line-height: 40px;">
      <td><h3>Parsing</h3></td><td />
    </tr>
    {{ form_row(form.LgParserType) }}
    {{ form_row(form.LgCharacterSubstitutions) }}
    {{ form_row(form.LgRegexpSplitSentences) }}
    {{ form_row(form.LgExceptionsSplitSentences) }}
    {{ form_row(form.LgRegexpWordCharacters) }}

    {# Currently hiding the below as Lute doesn't support these languages. #}
    {% if false %}
    {{ form_row(form.LgSplitEachChar) }}
    {{ form_row(form.LgRemoveSpaces) }}
    {{ form_row(form.LgRightToLeft) }}
    {% endif %}
    
  </tbody>
</table>


<button class="btn">Save</button>
{{ form_end(form) }}

templates/language/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Language{% endblock %}

{% block body %}
    <h1>Edit Language</h1>

    {{ include('language/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_language_index') }}">back to list</a>

    {{ include('language/_delete_form.html.twig') }}
{% endblock %}

templates/language/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Language index{% endblock %}

{% block body %}

<h1>Language index</h1>

{% if languages|length == 0 %}
  <p>No languages defined.</p>
{% else %}
  
<table class="table dataTable no-footer" style="width: 50%; margin: 0;">
  <thead>
    <tr>
      <th>Language</th>
      <th>Active Books</th>
      <th>Terms</th>
    </tr>
  </thead>
  <tbody>
    {% for language in languages %}
    <tr>
      <td>
        <a href="/language/{{ language.LgID }}/edit">
          {{ language.LgName }}
        </a>
      </td>
      <td>
        {% set ab = language.activeBooks|length %}
        {% if ab > 0 %}
        <a href="/book/index/{{ language.LgName }}">{{ ab }}</a>
        {% else %}
        -
        {% endif %}
      </td>
      <td>
        {% set ltl = language.terms|length %}
        {% if ltl > 0 %}
        <a href="/term/index/{{ language.LgName }}">{{ ltl }}</a>
        {% else %}
        -
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endif %}

<br />
<a href="{{ path('app_language_new') }}">Create new</a>
{% endblock %}

templates/language/lemma_import.html.twig
{% extends 'base.html.twig' %}

{% block title %}File exported{% endblock %}

{% block body %}

{% if error %}
<h1>Import error</h1>
<div style="width: 50%">
  <p><b>{{ error }}</b></p>
  <p>Please ensure you have created the input file as specified in the wiki -- ref <a href="https://github.com/jzohrab/lute/wiki/Bulk-Mapping-Parent-Terms">Bulk Mapping Parent Terms</a>.</p>
</div>
{% else %}

<h1>File imported</h1>

<p>Completed importing {{ infile }} of {{ language }} term mappings.</p>

<p>Results:
  <ul>
    <li>Created terms: {{ created }}</li>
    <li>Updated terms: {{ updated }}</li>
  </ul>
</p>

{% endif %}

{% endblock %}

templates/language/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Language{% endblock %}

{% block body %}
    <h1>Create new Language</h1>

    <p><i>Load from predefined:</i>
      <select id="predefined">
        {% for p in predefined %}
        <option value="{{ p }}">{{ p }}</option>
        {% endfor %}
      </select>
      <button onclick="location.href='/language/new/' + document.getElementById('predefined').value;">go</button>
    </p>

    <br />

    {{ include('language/_form.html.twig') }}

    <a href="{{ path('app_language_index') }}">back to list</a>
{% endblock %}