src/Entity/Text.php
<?php

namespace App\Entity;

use DateTime;
use App\Repository\TextRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TextRepository::class)]
#[ORM\Table(name: 'texts')]
class Text
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'TxID', type: Types::SMALLINT)]
    private ?int $TxID = null;

    #[ORM\Column(name: 'TxText', type: Types::TEXT)]
    private string $TxText = '';

    #[ORM\Column(name: 'TxOrder', type: Types::SMALLINT)]
    private int $TxOrder = 1;

    #[ORM\Column(name: 'TxReadDate', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTime $TxReadDate = null;

    #[ORM\ManyToOne(inversedBy: 'Texts')]
    #[ORM\JoinColumn(name: 'TxBkID', referencedColumnName: 'BkID', nullable: false)]
    private ?Book $book = null;

    #[ORM\OneToMany(mappedBy: 'text', targetEntity: Sentence::class, orphanRemoval: true, cascade: ['persist'], fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['SeOrder' => 'ASC'])]
    #[ORM\JoinColumn(name: 'SeTxID', referencedColumnName: 'TxID', nullable: false)]
    private Collection $Sentences;


    public function __construct()
    {
        $this->Sentences = new ArrayCollection();
    }


    public function getID(): ?int
    {
        return $this->TxID;
    }

    public function getTitle(): string
    {
        $b = $this->getBook();
        $s = "({$this->getOrder()}/{$b->getPageCount()})";
        $t = "{$b->getTitle()} {$s}";
        return $t;
    }

    public function getText(): string
    {
        return $this->TxText;
    }

    public function setText(string $TxText): self
    {
        $this->TxText = $TxText;
        $this->loadSentences();
        return $this;
    }

    public function setOrder(int $n): self
    {
        $this->TxOrder = $n;
        return $this;
    }

    public function getOrder(): int
    {
        return $this->TxOrder;
    }

    public function getLanguage(): ?Language
    {
        return $this->getBook()->getLanguage();
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getReadDate(): ?DateTime
    {
        return $this->TxReadDate;
    }

    public function setReadDate(?DateTime $dt): self
    {
        $this->TxReadDate = $dt;
        $this->loadSentences();
        return $this;
    }

    /** Sentences. */

    private function makeSentenceFromTokens($tokens, $senumber) {
        $ptstrings = array_map(fn($t) => $t->token, $tokens);

        $zws = mb_chr(0x200B); // zero-width space.
        $s = implode($zws, $ptstrings);
        $s = trim($s, ' ');

        // The zws is added at the start and end of each
        // sentence, to standardize the string search when
        // looking for terms.
        $s = $zws . $s . $zws;

        $sentence = new Sentence();
        $sentence->setSeOrder($senumber);
        $sentence->setSeText($s);
        return $sentence;
    }


    private function loadSentences() {
        foreach ($this->getSentences() as $s)
            $this->removeSentence($s);

        if ($this->TxReadDate == null)
            return;

        $lang = $this->getLanguage();
        $parser = $lang->getParser();
        $parsedtokens = $parser->getParsedTokens($this->TxText, $lang);

        $curr_sentence_tokens = [];
        $sentence_number = 1;

        foreach ($parsedtokens as $pt) {
            $curr_sentence_tokens[] = $pt;
            if ($pt->isEndOfSentence) {
                $se = $this->makeSentenceFromTokens($curr_sentence_tokens, $sentence_number);
                $this->addSentence($se);

                // Reset for next sentence.
                $curr_sentence_tokens = [];
                $sentence_number += 1;
            }
        }

        // Add any stragglers.
        if (count($curr_sentence_tokens) > 0) {
            $se = $this->makeSentenceFromTokens($curr_sentence_tokens, $sentence_number);
            $this->addSentence($se);
        }
    }

    /**
     * @return Collection<int, Sentence>
     */
    public function getSentences(): Collection
    {
        return $this->Sentences;
    }

    private function addSentence(Sentence $sentence): self
    {
        if (!$this->Sentences->contains($sentence)) {
            $this->Sentences->add($sentence);
            $sentence->setText($this);
        }
        return $this;
    }

    private function removeSentence(Sentence $sentence): self
    {
        if ($this->Sentences->removeElement($sentence)) {
            $sentence->setText(null);
        }
        return $this;
    }

}

src/Controller/TermController.php
<?php

namespace App\Controller;

use App\Entity\Term;
use App\Entity\Language;
use App\DTO\TermDTO;
use App\Form\TermDTOType;
use App\Repository\TermRepository;
use App\Repository\TermTagRepository;
use App\Repository\LanguageRepository;
use App\Domain\TermService;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/term')]
class TermController extends AbstractController
{
    #[Route('/index/{search?}', name: 'app_term_index', methods: ['GET'])]
    public function index(?string $search): Response
    {
        // Can pass an initial search string.  If nothing is passed, $search = null.
        return $this->render('term/index.html.twig', [
            'initial_search' => $search
        ]);
    }

    #[Route('/datatables', name: 'app_term_datatables', methods: ['POST'])]
    public function datatables_source(Request $request, TermRepository $repo): JsonResponse
    {
        $parameters = $request->request->all();
        $data = $repo->getDataTablesList($parameters);
        $data["draw"] = $parameters['draw'];
        return $this->json($data);
    }

    #[Route('/bulk_set_parent', name: 'app_term_bulk_set_parent', methods: ['POST'])]
    public function bulk_set_parent(
        Request $request,
        TermRepository $term_repo,
        LanguageRepository $lang_repo,
        TermService $term_svc
    ): JsonResponse
    {
        $parameters = $request->request->all();
        $wordids = $parameters['wordids'];
        $parenttext = trim($parameters['parenttext']);
        $langid = intval($parameters['langid']);

        $lang = $lang_repo->find($langid);
        $parent = null;
        if ($parenttext != '') {
            $parent = $term_svc->find($parenttext, $lang);
            if ($parent == null) {
                $parent = new Term($lang, $parenttext);
            }
        }
        $pid = null;
        if ($parent != null)
            $pid = $parent->getID();

        $terms = array_map(fn($n) => $term_repo->find(intval($n)), $wordids);
        $update = array_filter(
            $terms,
            fn($t) => ($t->getLanguage()->getLgID() == $langid) && ($t->getID() != $pid)
        );
        foreach ($update as $t) {
            $t->removeAllParents();
            $t->addParent($parent);
            $term_repo->save($t, true);
        }
        return $this->json('ok');
    }


    #[Route('/search/{text}/{langid}', name: 'app_term_search', methods: ['GET'])]
    public function search_by_text_in_language(
        $text,
        $langid,
        LanguageRepository $lang_repo,
        TermService $term_service
    ): JsonResponse
    {
        $lang = $lang_repo->find($langid);
        $terms = $term_service->findMatches($text, $lang);
        $result = [];
        foreach ($terms as $t) {
            $trans = $t->getTranslation();
            $result[] = [
                'id' => $t->getID(),
                'text' => $t->getText(),
                'translation' => $t->getTranslation()
            ];
        }
        return $this->json($result);
    }


    /** Note the form is passed by reference, may need to revert it to earlier state. */
    private function processTermForm(
        \Symfony\Component\Form\Form &$form,
        Request $request,
        TermDTO $termdto,
        TermService $term_svc,
        TermTagRepository $termtag_repo
    ): ?Response
    {
        $form->handleRequest($request);
        $submitted_valid = $form->isSubmitted() && $form->isValid();
        if (! $submitted_valid)
            return null;

        if ($termdto->textHasChanged()) {
            $msg = "Can only change term case.";
            $this->addFlash('error', $msg);
            $termdto->Text = $termdto->OriginalText;
            $form = $this->createForm(TermDTOType::class, $termdto);
            return null;
        }

        $term = TermDTO::buildTerm($termdto, $term_svc, $termtag_repo);
        try {
            $term_svc->add($term);
            return $this->redirectToRoute('app_term_index', [], Response::HTTP_SEE_OTHER);
        }
        catch (\Exception $e) {
            $errcode = intval($e->getCode());
            $INTEGRITY_CONSTRAINT_VIOLATION = 1062;
            if ($errcode != $INTEGRITY_CONSTRAINT_VIOLATION) {
                // Some different error, throw b/c I'm not sure what's
                // happening.
                throw $e;
            }

            $msg = $term->getText() . " already exists.";
            $this->addFlash('notice', $msg);
            $existing = $term_svc->find($term->getTextLC(), $term->getLanguage());
            return $this->redirectToRoute(
                'app_term_edit',
                [ 'id' => $existing->getID() ],
                Response::HTTP_SEE_OTHER
            );
        }
    }


    #[Route('/new', name: 'app_term_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TermService $term_svc, TermTagRepository $termtag_repo): Response
    {
        $dto = new TermDTO();
        $form = $this->createForm(TermDTOType::class, $dto);
        $resp = $this->processTermForm($form, $request, $dto, $term_svc, $termtag_repo);
        if ($resp != null)
            return $resp;

        return $this->renderForm('term/formframes.html.twig', [
            'termdto' => $dto,
            'form' => $form,
            'showlanguageselector' => true
        ]);
    }


    #[Route('/sentences/{LgID}/{text}', name: 'app_term_sentences', methods: ['GET'])]
    public function show_sentences(Language $lang, string $text, TermService $term_svc): Response
    {
        $term = $term_svc->find($text, $lang);
        if ($term == null)
            $term = new Term($lang, $text);
        $refs = $term_svc->findReferences($term);

        // Ref https://stackoverflow.com/questions/2517947/
        //  ucfirst-function-for-multibyte-character-encodings
        $mb_ucfirst = function ($string, $encoding = null)
        {
            if ($encoding === null)
                $encoding = mb_internal_encoding();
            $firstChar = mb_substr($string, 0, 1, $encoding);
            $then = mb_substr($string, 1, null, $encoding);
            return mb_strtoupper($firstChar, $encoding) . $then;
        };

        $ret = [
            $mb_ucfirst($term->getText()) => array_merge($refs['term'], $refs['children'])
        ];
        foreach ($refs['parents'] as $p) {
            $ptxt = $mb_ucfirst($p['term']);
            $ret[$ptxt] = $p['refs'];
        }
        return $this->render(
            'term/sentences.html.twig',
            [ 'references' => $ret ]
        );
    }


    #[Route('/{id}/edit', name: 'app_term_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Term $term, TermService $term_svc, TermTagRepository $termtag_repo): Response
    {
        $dto = $term->createTermDTO();
        $form = $this->createForm(TermDTOType::class, $dto);
        $resp = $this->processTermForm($form, $request, $dto, $term_svc, $termtag_repo);
        if ($resp != null)
            return $resp;

        return $this->renderForm('term/formframes.html.twig', [
            'termdto' => $dto,
            'form' => $form,
            'showlanguageselector' => false
        ]);
    }


    /**
     * Method used by the term form
     * (templates/term/_form.html.twig) to find the Term by text.
     *
     * A few hacky notes about this method:
     * - the zero-width-string cruft is included in the URL
     * - terms with '.' will throw due to Symfony not liking URLs with '.'
     *   To work around this, clients send __LUTE_PERIOD__ instead of '.'.
     */
    #[Route('/editbytext/{LgID}/{text}', name: 'app_term_edit_by_text', methods: ['GET', 'POST'])]
    public function editbytext(Request $request, Language $lang, string $text, TermService $term_svc, TermTagRepository $termtag_repo): Response
    {
        // Undo the "annoying hack" sent by lute.js to handle '.'
        // character.
        $usetext = preg_replace('/__LUTE_PERIOD__/u', '.', $text);
        $term = $term_svc->find($usetext, $lang);
        if ($term == null) {
            throw new \Exception("Missing expected term {$usetext}");
        }

        $dto = $term->createTermDTO();
        $form = $this->createForm(TermDTOType::class, $dto);
        $resp = $this->processTermForm($form, $request, $dto, $term_svc, $termtag_repo);
        if ($resp != null)
            return $resp;

        return $this->renderForm('term/formframes.html.twig', [
            'termdto' => $dto,
            'form' => $form,
            'showlanguageselector' => false
        ]);
    }


    #[Route('/{id}', name: 'app_term_delete', methods: ['POST'])]
    public function delete(Request $request, Term $term, TermService $term_svc): Response
    {
        $reqtok = $request->request->get('_token');
        if ($this->isCsrfTokenValid('delete'.$term->getId(), $reqtok)) {
            $term_svc->remove($term);
        }

        return $this->redirectToRoute('app_term_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/term/_delete_form.html.twig
<form method="post" action="{{ path('app_term_delete', {'id': termdto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ termdto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/term/_form.html.twig
{% form_theme form 'form_table_layout.html.twig' %}

{% for message in app.flashes('error') %}
<div class="flash-notice-narrow">
  {{ message }}
</div>
{% endfor %}

{{ form_start(form) }}

<table id="term">

  <tr id="languageSel"
    {% if ((showlanguageselector ?? false) != true) %}
      style="display:none;"
    {% endif %}
  >
    <td>{{ form_widget(form.language) }}</td>
  </tr>

  {{ form_widget(form.OriginalText) }}

  <tr>
    <td>
      {{ form_widget(form.Text) }}
    </td>
    <td style="white-space: nowrap;">
      <img src="/icn/external.png" title="Lookup" onclick="do_term_lookup()" />
      <img src="/icn/eye.png" title="Images" onclick="do_image_lookup()" />
    </td>
  </tr>

  {% do form.termParents.setRendered %}
  {# manually write list so it can be managed by tagit. #}
  <tr>
    <td>
      <ul id="parentslist" class="tags nomarginblock shorttaglist">
        {% for p in form.termParents %}
        <li>
          {{ p.vars.value }}
        </li>
        {% endfor %}
      </ul>
    </td>
  </tr>

  <tr>
    <td>
      {{ form_widget(form.Romanization, {'label':false}) }}
    </td>
  </tr>

  <tr>
    <td>{{ form_widget(form.Translation) }}</td>
    <td><img class="zoomableTermImage" id="term_image" src="{{ form.CurrentImage.vars.value }}" width="50px"/></td>
  </tr>

  <tr>
    <td>
      {{ form_widget(form.Status, {'label':false}) }}
    </td>
  </tr>
  <tr>
    <td>
      {{ form_row(form.CurrentImage, {'label':false}) }}
    </td>
  </tr>

  {% do form.termTags.setRendered %}
  {# manually write list so it can be managed by tagit. #}
  <tr>
    <td>
      <ul id="termtagslist" class="tags nomarginblock shorttaglist">
        {% for termTag in form.termTags %}
        <li>
          {{ termTag.vars.value }}
        </li>
        {% endfor %}
      </ul>
    </td>
  </tr>

  <tr>
    <td align="right">
      <a href="" onclick="show_term_sentences(); return false;">Sentences</a>
      <button class="btn">Save</button>
    </td>
  </tr>
</table>



{{ form_end(form) }}

<script type="text/javascript">

  // Preventing user navigating away by clicking on form parent tags.
  // Done with monitor_form and form_changed vars.
  // TODO acceptance tests; need to check interactions.  Painful.

  // Only start monitoring the form for changes after everything has
  // been initialized.  Tagit calls before/afterTagAdded etc during
  // initialization of the form, and we don't want those changes to
  // be treated as user-activated changes.
  let monitor_form = false;

  // Monitor state of form change (hacky, but seems to work).
  let form_changed = false;

  // This takes care of most controls, but not the tagit managed lists.
  $("form :input").change(function() {
    if (monitor_form)
      form_changed = true;
  });


  let setup_parent_Tagit = function() {
    var prototypeFieldName = 'term_dto[termParents][__name__]';
    var fieldIndex = 0;

    $('#parentslist').tagit(
      {
        placeholderText: 'Parents',
        beforeTagAdded: function (_event, ui) {
          fieldIndex++;
          $(this).tagit({fieldName: prototypeFieldName.replace('__name__', fieldIndex)});
        },
        afterTagAdded: function (_event, ui) {
          if (monitor_form) {
            form_changed = true;
          }
        },
        afterTagRemoved: function (_event, ui) {
          if (monitor_form) {
            form_changed = true;
          }
        },
        onTagClicked: function (evt, ui) {
          // Exit early if language not set - can't handle, too complicated.
          if ("{{ form.language.vars.value }}" == "") {
            return;
          }

          if (form_changed) {
            choice = confirm('You have unsaved changes, going to the parent will lose them.  Continue?');
            if (! choice) {
              return;
            }
          }

          let clickedtagtext = $('#parentslist').tagit('tagLabel', ui.tag);
          // Annoying hack.  I wanted to send a period '.' in the term, but
          // Symfony did not handle that well (per issue
          // https://github.com/jzohrab/lute/issues/28), and replacing the '.'
          // with the encoded value ('\u2e' or '%2E') did not work, as it kept
          // getting changed back to '.' on send, or it said that it could not
          // find the controller route.  There is probably something very
          // simple I am missing, but for now, replacing the '.' with a hacky
          // string which is replaced on server side as well.
          const periodhack = '__LUTE_PERIOD__';
          clickedtagtext = clickedtagtext.replaceAll('.', periodhack);
          if (clickedtagtext == '')
            return;

          // alert("You clicked me: " + clickedtagtext);
          // We should never reach this point if the lang is not set.
          const langid = {{ form.language.vars.value | default(-1) }};
          let url = '';
          {% if parent_link_to_frame ?? false %}
          url = `/read/termform/${langid}/${clickedtagtext}`;
          {% else %}
          url = `/term/editbytext/${langid}/${clickedtagtext}`;
          {% endif %}

          window.location = url;
        },

        fieldName: prototypeFieldName.replace('__name__', 0),
        allowSpaces: true,
        autocomplete: {
          source: function(request, response) {
            const s = encodeURIComponent(request.term);
            const langid = parseInt($('#term_dto_language').val());
            $.ajax({
              url: `/term/search/${s}/${langid}`,
              type: 'GET',
              dataType: 'json',
              minLength: 2,
              success: function(data) {
                arr = data.map(function(word) {
                  let label = word.text;
                  if (word.translation != null && word.translation != '') {
                    label = `${label} (${word.translation})`;
                  }
                  const obj = {
                    label: label,
                    value: word.text,
                    word: word.text,
                    translation: word.translation
                  };
                  return obj;
                });
                response(arr, data);
              } // end success
            }) // end ajax
          } // end source
        } // end autocomplete
      }
    );  // end tagit
  }


  let setupTagit = function() {
    // term_dto is what symfony calls the form.
    var prototypeFieldName = 'term_dto[termTags][__name__]';
    var fieldIndex = 0;
    
    let invalidChar = function(s) { return /[\uD800-\uDFFF]/.test(s); };

    $('#termtagslist').tagit(
      {
        placeholderText: 'Tags',
        beforeTagAdded: function (_event, ui) {
          if (invalidChar(ui.tag.text())) {
            return;
          }
          fieldIndex++;
          $(this).tagit({fieldName: prototypeFieldName.replace('__name__', fieldIndex)});
        },
        availableTags: TAGS,
        fieldName: 'term_dto[termTags][0]'
      });

  };

  let handleAutofocus = function() {
    const wordfield = $('#wordfield');
    const transfield = $('#translationfield');

    if ($('#autofocus').val() != 'false') {
      if (wordfield.val()) {
        transfield.focus();
      }
      else {
        wordfield.focus();
      }
    }

  }
  $(document).ready(function () {
    setup_parent_Tagit();
    setupTagit();

    // Approx good size for the text area:
    $('#term_dto_Translation').css({'width': '500px', 'height': '43px'});

    // Setup complete, can now start monitoring form.
    monitor_form = true;

    if (($('#term_dto_Text').val() ?? '') != '') {
      do_term_lookup(false);
    }
  });

  /** LOOKUPS */

  const LANGUAGES = {{ render(url('app_language_jsonlist')) }};

  // Term lookups cycle through the available dictionaries in the language.
  var termdictindex = 0;

  let open_new_lookup_window = function(url) {
    window.open(
      url,
      'otherwin',
      'width=800, height=400, scrollbars=yes, menubar=no, resizable=yes, status=no'
    );
  };

  let get_lookup_url = function(dicturl, term) {
    let ret = dicturl;

    // Terms are saved with zero-width space between each token;
    // remove that for dict searches!
    const zeroWidthSpace = '\u200b';
    const sqlZWS = '%E2%80%8B';
    const cleantext = term.
          replaceAll(zeroWidthSpace, '').
          replace(/\s+/g, ' ');
    const searchterm = encodeURIComponent(cleantext).
          replaceAll(sqlZWS, '');
    ret = ret.replace('###', searchterm);
    // console.log(ret);
    return ret;
  };


  let do_image_lookup = function() {
    const langid = $('#term_dto_language').val();
    const text = $('#term_dto_Text').val();

    if (langid == null || langid == '' || parseInt(langid) == 0 || text == null || text == '') {
      alert('Please select a language and enter the term.');
      return;
    }

    let use_text = text;

    // If there is a single parent, use that as the basis of the lookup.
    // Get text for all parent tags.
    // There is **likely** an easier way to get this with jquery!
    let parentTags = [];
    $('form input').each(
      function(index) {
        var input = $(this);
        let n = input.attr('name');
        if (typeof n !== "undefined" && n != null && n.startsWith('term_dto[termParents]')) {
           parentTags.push(input.val());
        }
    });
    let parent_text = null;
    if (parentTags.length == 1)
      use_text = parentTags[0];

    const raw_bing_url = 'https://www.bing.com/images/search?q=###&form=HDRSC2&first=1&tsc=ImageHoverTitle';
    const binghash = raw_bing_url.replace('https://www.bing.com/images/search?', '');
    const url = `/bing/search/${langid}/${encodeURIComponent(use_text)}/${encodeURIComponent(binghash)}`;
    top.frames.dictframe.location.href = url;
    return;
  }


  /**
   * Either open a new window, or show the result in the correct frame.
   */
  let show_lookup_page = function(dicturl, text, langid, allow_open_new_web_page = true) {

    const is_bing = (dicturl.indexOf('www.bing.com') != -1);
    if (is_bing) {
      let use_text = text;
      const binghash = dicturl.replace('https://www.bing.com/images/search?', '');
      const url = `/bing/search/${langid}/${encodeURIComponent(use_text)}/${encodeURIComponent(binghash)}`;
      top.frames.dictframe.location.href = url;
      return;
    }

    // TODO:fix_language_dict_asterisk
    // The URL shouldn not be prepended with trash
    // (e.g. "*http://" means "open an external window", while
    // "http://" means "this can be opened in an iframe."
    // Instead, each dict should have an "is_external" property.
    const is_external = (dicturl.charAt(0) == '*');
    if (is_external) {
      if (!allow_open_new_web_page) {
        console.log('Declining to open external web page.');
        return;
      }
      dicturl = dicturl.slice(1);
      const url = get_lookup_url(dicturl, text);
      open_new_lookup_window(url);
      return;
    }

    // Fallback: open in frame.
    const url = get_lookup_url(dicturl, text);
    top.frames.dictframe.location.href = url;
  };


  function do_term_lookup(allow_open_new_web_page = true) {
    const langid = $('#term_dto_language').val();
    if (langid == null || langid == '' || parseInt(langid) == 0) {
      alert('Please select a language.');
      return;
    }

    const termdicts = LANGUAGES[langid].term;
    const usedict = termdicts[termdictindex];
    show_lookup_page(usedict, $('#term_dto_Text').val(), langid, allow_open_new_web_page);

    termdictindex++;
    if (termdictindex >= termdicts.length)
      termdictindex = 0;
  }

  function show_term_sentences() {
    const langid = $('#term_dto_language').val();
    const txt = $('#term_dto_Text').val();
    // %E2%80%8B is the zero-width string.  The term is reparsed
    // on the server, so this doesn't need to be sent.
    const t = encodeURIComponent(txt).replaceAll('%E2%80%8B', '');
    const url = `/term/sentences/${langid}/${t}`;
    top.frames.dictframe.location.href = url;
  }

</script>

templates/term/formframes.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div id="form-frame-left" style="width: 50%;">
  {% if not showlanguageselector %}
  <h1>Edit Term</h1>
  {% else %}
  <h1>New Term</h1>
  {% endif %}

  {{ include('term/_form.html.twig', {'button_label': 'Update'}) }}

  <a href="{{ path('app_term_index') }}">back to list</a>

  {% if not showlanguageselector %}
  {{ include('term/_delete_form.html.twig') }}
  {% endif %}

</div>


<div id="reading-frames-right" style="position: fixed; top: 0; right: 0; height: 95%; 
width: 50%;">
  <iframe name="dictframe" class="rightreadingframe" src="/read/empty" scrolling="auto"
          style="height: 100%; width: 100%;" frameBorder="1">
    Frame support required.
  </iframe>
</div>

{% endblock %}

templates/term/sentences.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Sentences</title>
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />
    <style>
      p {
          font-style: italic;
      }
    </style>

    <script>
      function open_sentence_text(textid) {
        window.open(`/read/${textid}`, '_blank');
      }
    </script>

  </head>

  <body>

    {% for k, dtos in references %}
    {% if dtos|length > 0 %}
    <p>{{ k }}</p>
    <ul class="sentencelist">
      {% for dto in dtos %}
      <li style="margin-top: 4px;">
        {{ dto.Sentence | raw }}
        <br/>
        <a onclick="open_sentence_text({{ dto.TxID }});" style="cursor: pointer; font-size: 0.9em; font-style: italic;">{{ dto.Title }}</a>
      </li>
      {% endfor %}
    </ul>
    {% endif %}
    {% endfor %}

  </body>

</html>